<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="liga">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="jornada">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="partido" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="fecha" type="xs:date"/>
                                        <xs:element name="equipo" maxOccurs="2">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string"/>
                                                    <xs:element name="goles" type="xs:integer"/>
                                                </xs:sequence>
                                                <xs:attribute name="tipo" type="xs:string"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="estadio" type="xs:string"/>
                                        <xs:element name="estado" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>